services:
  orders-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
      - ./scripts/orders_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders"]
      interval: 5s
      timeout: 5s
      retries: 5

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    depends_on:
      orders-db:
        condition: service_healthy
    ports:
      - "4444:4444"

  auth-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth_db
    ports:
      - "6433:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data
      - ./scripts/auth_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - AUTH_DB_CONN_STR=postgres://auth:auth@auth-db:5432/auth_db
    ports:
      - "5555:5555"
    env_file:
      - ./auth/.env

volumes:
  orders_data:
  auth_db:
