syntax = "proto3";

package product;

option go_package = "ecommerce/api/gen/product;productpb";

message Product {
  string name = 1;
  double price = 2;
  uint32 quantity = 3;
}

message CreateProductRequest { Product product = 1; }

message CreateProductResponse { Product product = 1; }

message GetProductsRequest { repeated Product products = 1; }

message GetProductsResponse { repeated Product products = 1; }

service ProductService {
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);
  rpc GetProduct(GetProductsRequest) returns (GetProductsResponse);
}
