syntax = "proto3";

package stock;

option go_package = "ecommerce/api/gen/stock;stockpb";

message CheckStockRequest {
  string product_id = 1;
  int32 quantity = 2;
}

message CheckStockResponse {
  bool is_available = 1;
  int32 current_stock = 2;
}

message ReserveStockItem {
  string product_id = 1;
  int32 quantity = 2;
}

message ReserveStockRequest {
  string order_id = 1;
  repeated ReserveStockItem items = 2;
}

message ReserveStockResponse {
  bool success = 1;
  string message = 2;
}

service StockService {
  rpc CheckStock(CheckStockRequest) returns (CheckStockResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
}
